AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  notification-service

  Sample SAM Template for notification-service

Parameters:
  FIREBASE_API_KEY:
    Type: String
  FIREBASE_AUTH_DOMAIN:
    Type: String
  FIREBASE_PROJECT_ID:
    Type: String
  FIREBASE_STORAGE_BUCKET:
    Type: String
  FIREBASE_MESSAGING_SENDER_ID:
    Type: String
  FIREBASE_APP_ID:
    Type: String
  FIREBASE_MEASUREMENT_ID:
    Type: String
  FIREBASE_ADMIN_CREDS:
    Type: String
  FIREBASE_AUTH_EMULATOR_HOST:
    Type: String
  STAGE:
    Type: String
  DB_ACCESS_KEY_ID:
    Type: String
  DB_SECRET_ACCESS_KEY:
    Type: String
  DB_REGION:
    Type: String
  DB_ENDPOINT:
    Type: String
  DB_TABLE_NAME:
    Type: String
  MESSAGE_QUEUE_STREAM_ARN:
    Type: String
  MESSAGE_QUEUE_NAME:
    Type: String


# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15    
    MemorySize: 2048

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON

    Environment:
      Variables:
        FIREBASE_API_KEY: !Ref FIREBASE_API_KEY
        FIREBASE_AUTH_DOMAIN: !Ref FIREBASE_AUTH_DOMAIN
        FIREBASE_PROJECT_ID: !Ref FIREBASE_PROJECT_ID
        FIREBASE_STORAGE_BUCKET: !Ref FIREBASE_STORAGE_BUCKET
        FIREBASE_MESSAGING_SENDER_ID: !Ref FIREBASE_MESSAGING_SENDER_ID
        FIREBASE_APP_ID: !Ref FIREBASE_APP_ID
        FIREBASE_MEASUREMENT_ID: !Ref FIREBASE_MEASUREMENT_ID
        FIREBASE_ADMIN_CREDS: !Ref FIREBASE_ADMIN_CREDS
        FIREBASE_AUTH_EMULATOR_HOST: !Ref FIREBASE_AUTH_EMULATOR_HOST
        STAGE: !Ref STAGE
        DB_ACCESS_KEY_ID: !Ref DB_ACCESS_KEY_ID
        DB_SECRET_ACCESS_KEY: !Ref DB_SECRET_ACCESS_KEY
        DB_REGION: !Ref DB_REGION
        DB_ENDPOINT: !Ref DB_ENDPOINT
        DB_TABLE_NAME: !Ref DB_TABLE_NAME
        TOKEN_TTL_DAYS: 270
        MESSAGE_QUEUE_STREAM_ARN: !Ref MESSAGE_QUEUE_STREAM_ARN
        MESSAGE_QUEUE_NAME: !Ref MESSAGE_QUEUE_NAME

Resources:
  NotifyJoinRequestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handler.main
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      Events:
        Notify:
          Type: DynamoDB
          Properties:
            Stream: !Ref MESSAGE_QUEUE_STREAM_ARN
            BatchSize: 100
            StartingPosition: LATEST
            Enabled: true
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - functions/notify-join-request/handler.ts
        External:
        - node_modules

  UpdateDeviceTokenFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handler.main
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      Events:
        Notify:
          Type: Api # change to stream
          Properties:
            Path: /tokens
            Method: put
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - functions/update-token/handler.ts
        External:
        - node_modules
  
  Splitsies-UserDeviceToken:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: !Ref DB_TABLE_NAME
      AttributeDefinitions: 
        - AttributeName: userId
          AttributeType: S
        - AttributeName: deviceToken
          AttributeType: S
      KeySchema: 
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: deviceToken
          KeyType: RANGE
      BillingMethod: PAY_PER_REQUEST


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  NotificationServiceApi:
    Description: API Gateway endpoint URL for NotificationService
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${STAGE}/"
  NotifyJoinRequestFunction:
    Description: Notify Lambda Function ARN
    Value: !GetAtt NotifyJoinRequestFunction.Arn
  NotifyJoinRequestFunctionIamRole:
    Description: Implicit IAM Role created for Notify function
    Value: !GetAtt NotifyJoinRequestFunctionRole.Arn
  AddUserDeviceTokenFunction:
    Description: Notify Lambda Function ARN
    Value: !GetAtt AddUserDeviceTokenFunction.Arn
  AddUserDeviceTokenFunctionIamRole:
    Description: Implicit IAM Role created for Notify function
    Value: !GetAtt AddUserDeviceTokenFunctionRole.Arn
