AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  notification-service

  SAM Template for notification-service

Parameters:
  FirebaseApiKey:
    Type: String
  FirebaseAuthDomain:
    Type: String
  FirebaseProjectId:
    Type: String
  FirebaseStorageBucket:
    Type: String
  FirebaseMessagingSenderId:
    Type: String
  FirebaseAppId:
    Type: String
  FirebaseMeasurementId:
    Type: String
  FirebaseAdminCreds:
    Type: String
  Stage:
    Type: String
  DbAccessKeyId:
    Type: String
  DbSecretAccessKey:
    Type: String
  DbRegion:
    Type: String
  DbEndpoint:
    Type: String
  DbTableName:
    Type: String
  MessageQueueStreamArn:
    Type: String
  MessageQueueName:
    Type: String
  JoinRequestNotificationQueue:
    Type: String
    Default: 39E552E9-0045-4210-9582-80E96553F95C


# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15    
    MemorySize: 2048

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON

    Environment:
      Variables:
        FIREBASE_API_KEY: !Ref FirebaseApiKey
        FIREBASE_AUTH_DOMAIN: !Ref FirebaseAuthDomain
        FIREBASE_PROJECT_ID: !Ref FirebaseProjectId
        FIREBASE_STORAGE_BUCKET: !Ref FirebaseStorageBucket
        FIREBASE_MESSAGING_SENDER_ID: !Ref FirebaseMessagingSenderId
        FIREBASE_APP_ID: !Ref FirebaseAppId
        FIREBASE_MEASUREMENT_ID: !Ref FirebaseMeasurementId
        FIREBASE_ADMIN_CREDS: !Ref FirebaseAdminCreds
        STAGE: !Ref Stage
        DB_ACCESS_KEY_ID: !Ref DbAccessKeyId
        DB_SECRET_ACCESS_KEY: !Ref DbSecretAccessKey
        DB_REGION: !Ref DbRegion
        DB_ENDPOINT: !Ref DbEndpoint
        DB_TABLE_NAME: !Ref DbTableName
        TOKEN_TTL_DAYS: 270
        MESSAGE_QUEUE_NAME: !Ref MessageQueueName

Resources:
  ServerlessRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage

  NotifyJoinRequestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handler.main
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      Events:
        Notify:
          Type: DynamoDB
          Properties:
            Stream: !Ref MessageQueueStreamArn
            MaximumRetryAttempts: 3
            MaximumRecordAgeInSeconds: 60
            StartingPosition: LATEST
            Enabled: true
            FilterCriteria:
              Filters:
                - Pattern: !Sub "{ \"eventName\": [\"INSERT\"], \"dynamodb\" : { \"Keys\" : { \"queueName\" : { \"S\" : [ \"${JoinRequestNotificationQueue}\" ] } } } }"
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - functions/notify-join-request/handler.ts
        External:
        - node_modules

  UpdateDeviceTokenFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handler.main
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      Events:
        Notify:
          Type: Api # change to stream
          Properties:
            Path: /v1/tokens
            Method: put
            RestApiId: !Ref ServerlessRestApi
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - functions/update-token/handler.ts
        External:
        - node_modules
  
  UserDeviceTokenTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: !Ref DbTableName
      AttributeDefinitions: 
        - AttributeName: userId
          AttributeType: S
        - AttributeName: deviceToken
          AttributeType: S
      KeySchema: 
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: deviceToken
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  NotificationServiceApi:
    Description: API Gateway endpoint URL for NotificationService
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/"
  NotifyJoinRequestFunction:
    Description: Notify Lambda Function ARN
    Value: !GetAtt NotifyJoinRequestFunction.Arn
  NotifyJoinRequestFunctionIamRole:
    Description: Implicit IAM Role created for Notify function
    Value: !GetAtt NotifyJoinRequestFunctionRole.Arn
  UpdateDeviceTokenFunction:
    Description: Notify Lambda Function ARN
    Value: !GetAtt UpdateDeviceTokenFunction.Arn
  UpdateDeviceTokenFunctionIamRole:
    Description: Implicit IAM Role created for Notify function
    Value: !GetAtt UpdateDeviceTokenFunctionRole.Arn
  UserDeviceTokenTable:
    Description: Table ARN
    Value: !GetAtt UserDeviceTokenTable.Arn
