AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  notification-service database

  SAM Template for notification-service database

Parameters:
  dbTableName:
    Type: String

Resources:  
  UserDeviceTokenTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: !Ref dbTableName
      AttributeDefinitions: 
        - AttributeName: userId
          AttributeType: S
        - AttributeName: deviceToken
          AttributeType: S
      KeySchema: 
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: deviceToken
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: gsiDeviceToken
          KeySchema:
            - AttributeName: deviceToken
              KeyType: HASH
            - AttributeName: userId
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
