AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  notification-service database

  SAM Template for notification-service database

Parameters:
  StagingLambdaExecutionRoleArn:
    Type: String
  DbRegion:
    Type: String
    Default: us-east-1

Resources:  
  UserDeviceTokenTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: UserDeviceToken
      AttributeDefinitions: 
        - AttributeName: userId
          AttributeType: S
        - AttributeName: deviceToken
          AttributeType: S
      KeySchema: 
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: deviceToken
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: gsiDeviceToken
          KeySchema:
            - AttributeName: deviceToken
              KeyType: HASH
            - AttributeName: userId
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
      ResourcePolicy:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                AWS: !Sub ${StagingLambdaExecutionRoleArn}/*
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Query
                - dynamodb:Scan
              Resource: 
                - !Sub arn:aws:dynamodb:${DbRegion}:${AWS::AccountId}:table/UserDeviceToken
