name: Deploy Dev

on:
  pull_request:
    branches:
      - main
      - "releases/**"

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/setup-python@v3
    - uses: aws-actions/setup-sam@v2
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.SPLITSIES_DEPLOY_ACCESS_KEY_ID_DEV }}
        aws-secret-access-key: ${{ secrets.SPLITSIES_DEPLOY_SECRET_KEY_DEV }}
        aws-region: us-east-1


    - run: npm ci
      working-directory: ./api    
    - run: sam build
      working-directory: ./api
    - run: |
        sam deploy --stack-name notification-service \
        --no-confirm-changeset \
        --no-fail-on-empty-changeset \
        --parameter-overrides \
          "Stage=dev" \
          "dbRegion=us-east-1" \
          "dbEndpoint=https://dynamodb.us-east-1.amazonaws.com/" \
          "ResourceAccountId=${{ secrets.DEV_ACCOUNT_ID }}" \
          "MessageQueueStreamArn=${{ secrets.MESSAGE_QUEUE_ARN_DEV_PR }}" \
          "FirebaseApiKey=${{ secrets.FIREBASE_API_KEY_DEV_PR }}" \
          "FirebaseAuthDomain=${{ secrets.FIREBASE_AUTH_DOMAIN_DEV_PR }}" \
          "FirebaseProjectId=${{ secrets.FIREBASE_PROJECT_ID_DEV_PR }}" \
          "FirebaseStorageBucket=${{ secrets.FIREBASE_STORAGE_BUCKET_DEV_PR }}" \
          "FirebaseMessagingSenderId=${{ secrets.FIREBASE_MESSAGING_SENDER_ID_DEV_PR }}" \
          "FirebaseAppId=${{ secrets.FIREBASE_APP_ID_DEV_PR }}" \
          "FirebaseMeasurementId=${{ secrets.FIREBASE_MEASUREMENT_ID_DEV_PR }}" \
          "FirebaseAdminCreds=${{ secrets.FIREBASE_ADMIN_CREDS_DEV_PR }}"
      working-directory: ./api


    - run: sam build
      working-directory: ./database
    - run: |
        sam deploy --stack-name notification-service-database \
        --no-confirm-changeset \
        --no-fail-on-empty-changeset \
        --parameter-overrides "StagingLambdaExecutionRoleArn=${{ secrets.SPLITSIES_NOTIFICATION_SERVICE_LAMBDA_EXECUTION_ROLE_ARN }}"
      working-directory: ./database
